language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
    - composer self-update
    - composer install

script:
  - vendor/bin/phpcs --standard=psr2 --extensions=php --ignore=vendor .
  - vendor/bin/phpunit --coverage-text

