language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

matrix:
  allow_failures:
    - php: nightly

before_install:
  - composer self-update

install:
  - composer update $PREFER_LOWEST

script:
  - vendor/bin/phpcs --standard=psr2 --extensions=php --ignore=vendor .
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

