language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_install:
  - composer self-update

install:
  - composer install

script:
  - vendor/bin/phpcs --standard=psr2 --extensions=php --ignore=vendor .
  - vendor/bin/phpunit --coverage-text

